# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zeus.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(832, 603)
        MainWindow.setMinimumSize(QtCore.QSize(832, 603))
        MainWindow.setMaximumSize(QtCore.QSize(900, 650))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/marca/icons8-j-20.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(77, 77, 77);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(832, 562))
        self.centralwidget.setStyleSheet("background-color: rgb(66, 70, 81);")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.f_pai = QtWidgets.QFrame(self.centralwidget)
        self.f_pai.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_pai.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_pai.setObjectName("f_pai")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.f_pai)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.f_pai_zimage = QtWidgets.QFrame(self.f_pai)
        self.f_pai_zimage.setMaximumSize(QtCore.QSize(16777215, 150))
        self.f_pai_zimage.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_pai_zimage.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_pai_zimage.setObjectName("f_pai_zimage")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.f_pai_zimage)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.zeus_image = QtWidgets.QGraphicsView(self.f_pai_zimage)
        self.zeus_image.setMinimumSize(QtCore.QSize(270, 130))
        self.zeus_image.setMaximumSize(QtCore.QSize(270, 130))
        self.zeus_image.setStyleSheet("background-image: url(:/background/ZEUS.png);\n"
"background-repeat: no")
        self.zeus_image.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.zeus_image.setObjectName("zeus_image")
        self.gridLayout_3.addWidget(self.zeus_image, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.f_pai_zimage, 0, 0, 1, 1)
        self.f_pai_baixo = QtWidgets.QFrame(self.f_pai)
        self.f_pai_baixo.setMinimumSize(QtCore.QSize(812, 266))
        self.f_pai_baixo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_pai_baixo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_pai_baixo.setObjectName("f_pai_baixo")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.f_pai_baixo)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.f_pai_esquerdo = QtWidgets.QFrame(self.f_pai_baixo)
        self.f_pai_esquerdo.setMaximumSize(QtCore.QSize(500, 16777215))
        self.f_pai_esquerdo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_pai_esquerdo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_pai_esquerdo.setObjectName("f_pai_esquerdo")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.f_pai_esquerdo)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.l_digitelink = QtWidgets.QLabel(self.f_pai_esquerdo)
        self.l_digitelink.setMinimumSize(QtCore.QSize(382, 27))
        self.l_digitelink.setObjectName("l_digitelink")
        self.gridLayout_5.addWidget(self.l_digitelink, 0, 0, 1, 1)
        self.f_meio_cima_direita = QtWidgets.QFrame(self.f_pai_esquerdo)
        self.f_meio_cima_direita.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_meio_cima_direita.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_meio_cima_direita.setObjectName("f_meio_cima_direita")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.f_meio_cima_direita)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(50)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.line_link = QtWidgets.QLineEdit(self.f_meio_cima_direita)
        self.line_link.setMaximumSize(QtCore.QSize(250, 16777215))
        self.line_link.setStyleSheet("padding: 4px;\n"
"background-color: rgb(225, 225, 225);")
        self.line_link.setObjectName("line_link")
        self.horizontalLayout.addWidget(self.line_link)
        self.pb_verificar = QtWidgets.QPushButton(self.f_meio_cima_direita)
        self.pb_verificar.setObjectName("pb_verificar")
        self.horizontalLayout.addWidget(self.pb_verificar)
        self.gridLayout_5.addWidget(self.f_meio_cima_direita, 1, 0, 1, 1)
        self.f_filho_baixo = QtWidgets.QFrame(self.f_pai_esquerdo)
        self.f_filho_baixo.setMinimumSize(QtCore.QSize(382, 350))
        self.f_filho_baixo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_filho_baixo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_filho_baixo.setObjectName("f_filho_baixo")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.f_filho_baixo)
        self.verticalLayout.setObjectName("verticalLayout")
        self.f_sub_baixo = QtWidgets.QFrame(self.f_filho_baixo)
        self.f_sub_baixo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_sub_baixo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_sub_baixo.setObjectName("f_sub_baixo")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.f_sub_baixo)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.f_filho_subaixo = QtWidgets.QFrame(self.f_sub_baixo)
        self.f_filho_subaixo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_filho_subaixo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_filho_subaixo.setObjectName("f_filho_subaixo")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.f_filho_subaixo)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.f_paimusic = QtWidgets.QFrame(self.f_filho_subaixo)
        self.f_paimusic.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_paimusic.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_paimusic.setObjectName("f_paimusic")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.f_paimusic)
        self.gridLayout_9.setContentsMargins(0, 5, 5, -1)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.f_filho_cima_music = QtWidgets.QFrame(self.f_paimusic)
        self.f_filho_cima_music.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_filho_cima_music.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_filho_cima_music.setObjectName("f_filho_cima_music")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.f_filho_cima_music)
        self.gridLayout_10.setObjectName("gridLayout_10")
        spacerItem = QtWidgets.QSpacerItem(82, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(82, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem1, 0, 0, 1, 1)
        self.f_fot_music = QtWidgets.QFrame(self.f_filho_cima_music)
        self.f_fot_music.setMinimumSize(QtCore.QSize(131, 91))
        self.f_fot_music.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_fot_music.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_fot_music.setObjectName("f_fot_music")
        self.gridLayout_10.addWidget(self.f_fot_music, 0, 1, 1, 1)
        self.gridLayout_9.addWidget(self.f_filho_cima_music, 0, 0, 1, 2)
        self.pb_play = QtWidgets.QPushButton(self.f_paimusic)
        self.pb_play.setObjectName("pb_play")
        self.gridLayout_9.addWidget(self.pb_play, 2, 0, 1, 1)
        self.pb_stop = QtWidgets.QPushButton(self.f_paimusic)
        self.pb_stop.setObjectName("pb_stop")
        self.gridLayout_9.addWidget(self.pb_stop, 2, 1, 1, 1)
        self.hslider_music = QtWidgets.QSlider(self.f_paimusic)
        self.hslider_music.setOrientation(QtCore.Qt.Horizontal)
        self.hslider_music.setObjectName("hslider_music")
        self.gridLayout_9.addWidget(self.hslider_music, 1, 0, 1, 2)
        self.gridLayout_8.addWidget(self.f_paimusic, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.f_filho_subaixo, 1, 0, 1, 2)
        self.frame = QtWidgets.QFrame(self.f_sub_baixo)
        self.frame.setMinimumSize(QtCore.QSize(342, 72))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.rb_playlist = QtWidgets.QRadioButton(self.frame)
        self.rb_playlist.setMinimumSize(QtCore.QSize(168, 17))
        self.rb_playlist.setObjectName("rb_playlist")
        self.gridLayout_12.addWidget(self.rb_playlist, 0, 0, 1, 1)
        self.rb_umarq = QtWidgets.QRadioButton(self.frame)
        self.rb_umarq.setMinimumSize(QtCore.QSize(168, 17))
        self.rb_umarq.setObjectName("rb_umarq")
        self.gridLayout_12.addWidget(self.rb_umarq, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame, 0, 0, 1, 2)
        self.verticalLayout.addWidget(self.f_sub_baixo)
        self.f_pai_download = QtWidgets.QFrame(self.f_filho_baixo)
        self.f_pai_download.setMinimumSize(QtCore.QSize(362, 40))
        self.f_pai_download.setMaximumSize(QtCore.QSize(16777215, 40))
        self.f_pai_download.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_pai_download.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_pai_download.setObjectName("f_pai_download")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.f_pai_download)
        self.gridLayout_11.setObjectName("gridLayout_11")
        spacerItem2 = QtWidgets.QSpacerItem(177, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem2, 0, 0, 1, 1)
        self.pb_download = QtWidgets.QPushButton(self.f_pai_download)
        self.pb_download.setObjectName("pb_download")
        self.gridLayout_11.addWidget(self.pb_download, 0, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.f_pai_download)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_11.addWidget(self.pushButton, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.f_pai_download)
        self.gridLayout_5.addWidget(self.f_filho_baixo, 2, 0, 1, 1)
        self.gridLayout_4.addWidget(self.f_pai_esquerdo, 0, 0, 1, 1)
        self.f_pai_direito = QtWidgets.QFrame(self.f_pai_baixo)
        self.f_pai_direito.setMinimumSize(QtCore.QSize(402, 386))
        self.f_pai_direito.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_pai_direito.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_pai_direito.setObjectName("f_pai_direito")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.f_pai_direito)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.barradeprogresso = QtWidgets.QProgressBar(self.f_pai_direito)
        self.barradeprogresso.setMinimumSize(QtCore.QSize(301, 23))
        self.barradeprogresso.setMaximumSize(QtCore.QSize(301, 23))
        self.barradeprogresso.setProperty("value", 0)
        self.barradeprogresso.setObjectName("barradeprogresso")
        self.gridLayout_6.addWidget(self.barradeprogresso, 5, 1, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(69, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 1, 0, 1, 1)
        self.l_thumbnail = QtWidgets.QLabel(self.f_pai_direito)
        self.l_thumbnail.setMaximumSize(QtCore.QSize(250, 20))
        self.l_thumbnail.setAlignment(QtCore.Qt.AlignCenter)
        self.l_thumbnail.setObjectName("l_thumbnail")
        self.gridLayout_6.addWidget(self.l_thumbnail, 0, 1, 1, 1)
        self.gpv_background = QtWidgets.QGraphicsView(self.f_pai_direito)
        self.gpv_background.setMaximumSize(QtCore.QSize(256, 201))
        self.gpv_background.setObjectName("gpv_background")
        self.gridLayout_6.addWidget(self.gpv_background, 1, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(69, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem4, 1, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(19, 14, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_6.addItem(spacerItem5, 3, 1, 1, 1)
        self.l_titulo = QtWidgets.QLabel(self.f_pai_direito)
        self.l_titulo.setMaximumSize(QtCore.QSize(16777215, 20))
        self.l_titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.l_titulo.setObjectName("l_titulo")
        self.gridLayout_6.addWidget(self.l_titulo, 2, 1, 1, 1)
        self.gridLayout_4.addWidget(self.f_pai_direito, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.f_pai_baixo, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.f_pai, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 832, 21))
        self.menubar.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.menubar.setObjectName("menubar")
        self.menuConfig = QtWidgets.QMenu(self.menubar)
        self.menuConfig.setObjectName("menuConfig")
        self.menuDownload = QtWidgets.QMenu(self.menuConfig)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons_menu/downloads.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuDownload.setIcon(icon1)
        self.menuDownload.setObjectName("menuDownload")
        self.menuAjuda = QtWidgets.QMenu(self.menubar)
        self.menuAjuda.setObjectName("menuAjuda")
        MainWindow.setMenuBar(self.menubar)
        self.ac_Manual = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons_menu/manual.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ac_Manual.setIcon(icon2)
        self.ac_Manual.setObjectName("ac_Manual")
        self.ac_Geral = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons_menu/config.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ac_Geral.setIcon(icon3)
        self.ac_Geral.setObjectName("ac_Geral")
        self.actionContato = QtWidgets.QAction(MainWindow)
        self.actionContato.setObjectName("actionContato")
        self.ac_Caminho_padrao = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons_menu/pasta.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ac_Caminho_padrao.setIcon(icon4)
        self.ac_Caminho_padrao.setObjectName("ac_Caminho_padrao")
        self.ac_Configurar = QtWidgets.QAction(MainWindow)
        self.ac_Configurar.setObjectName("ac_Configurar")
        self.actionContato_2 = QtWidgets.QAction(MainWindow)
        self.actionContato_2.setObjectName("actionContato_2")
        self.actionRedes_Sociais = QtWidgets.QAction(MainWindow)
        self.actionRedes_Sociais.setObjectName("actionRedes_Sociais")
        self.ac_Quem_somos = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons_menu/icons8-contato-comercial-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ac_Quem_somos.setIcon(icon5)
        self.ac_Quem_somos.setObjectName("ac_Quem_somos")
        self.menuDownload.addAction(self.ac_Caminho_padrao)
        self.menuDownload.addAction(self.ac_Configurar)
        self.menuConfig.addAction(self.ac_Geral)
        self.menuConfig.addAction(self.menuDownload.menuAction())
        self.menuAjuda.addAction(self.ac_Quem_somos)
        self.menuAjuda.addSeparator()
        self.menuAjuda.addAction(self.ac_Manual)
        self.menubar.addAction(self.menuConfig.menuAction())
        self.menubar.addAction(self.menuAjuda.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ZEUS - by Jefter"))
        self.l_digitelink.setText(_translate("MainWindow", "DIGITE O LINK ABAIXO:"))
        self.line_link.setPlaceholderText(_translate("MainWindow", "link"))
        self.pb_verificar.setText(_translate("MainWindow", "VERIFICAR"))
        self.pb_play.setText(_translate("MainWindow", "PLAY"))
        self.pb_stop.setText(_translate("MainWindow", "STOP"))
        self.rb_playlist.setText(_translate("MainWindow", "Playlist"))
        self.rb_umarq.setText(_translate("MainWindow", "Um arquivo"))
        self.pb_download.setText(_translate("MainWindow", "Poximo"))
        self.pushButton.setText(_translate("MainWindow", "Voltar"))
        self.l_thumbnail.setText(_translate("MainWindow", "THUMBNAIL"))
        self.l_titulo.setText(_translate("MainWindow", "TITULO"))
        self.menuConfig.setTitle(_translate("MainWindow", "Configurações"))
        self.menuDownload.setTitle(_translate("MainWindow", "Download"))
        self.menuAjuda.setTitle(_translate("MainWindow", "Ajuda"))
        self.ac_Manual.setText(_translate("MainWindow", "Manual"))
        self.ac_Geral.setText(_translate("MainWindow", "Geral"))
        self.actionContato.setText(_translate("MainWindow", "Contato"))
        self.ac_Caminho_padrao.setText(_translate("MainWindow", "Caminho padrão"))
        self.ac_Configurar.setText(_translate("MainWindow", "Configurar"))
        self.actionContato_2.setText(_translate("MainWindow", "Contato"))
        self.actionRedes_Sociais.setText(_translate("MainWindow", "Redes Sociais"))
        self.ac_Quem_somos.setText(_translate("MainWindow", "Quem somos"))
import imagens


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
